#!/bin/bash

# This script simulates the GitHub workflow locally
#
# Usage:
#   ./run_ci_locally.sh                         # Run all checks
#   ./run_ci_locally.sh --ignore-slither        # Run all checks but ignore Slither failures
#   ./run_ci_locally.sh --html-coverage         # Generate HTML coverage report
#   ./run_ci_locally.sh --run-coverage-anyway   # Run coverage even if tests fail
#   ./run_ci_locally.sh --help                  # Show this help message
#
# Environment variables:
#   FORK_URL    URL of the Ethereum node to fork (for tests and coverage)
#   ETH_RPC_URL Alternative to FORK_URL
#
# Note: Coverage reports generated by this script should NOT be committed to Git.
#       The following directories are added to .gitignore:
#       - coverage-report/
#       - coverage-final/
#       - lcov.info

# Show help if requested
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  echo "Usage:"
  echo "  ./run_ci_locally.sh                         # Run all checks"
  echo "  ./run_ci_locally.sh --ignore-slither        # Run all checks but ignore Slither failures"
  echo "  ./run_ci_locally.sh --html-coverage         # Generate HTML coverage report"
  echo "  ./run_ci_locally.sh --run-coverage-anyway   # Run coverage even if tests fail"
  echo "  ./run_ci_locally.sh --help                  # Show this help message"
  echo ""
  echo "Environment variables:"
  echo "  FORK_URL    URL of the Ethereum node to fork (for tests and coverage)"
  echo "  ETH_RPC_URL Alternative to FORK_URL"
  exit 0
fi

cd . || exit

# Load environment variables from .env file if it exists
if [ -f ".env" ]; then
  echo "Loading environment variables from .env file..."
  set -a
  source .env
  set +a
fi

# Set colors for pretty output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Function to show a spinner during long-running operations
spinner() {
  local pid=$1
  local delay=0.1
  local spinstr='|/-\'
  while [ "$(ps -p $pid -o pid=)" ]; do
    local temp=${spinstr#?}
    printf " [%c]  " "$spinstr"
    local spinstr=$temp${spinstr%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done
  printf "    \b\b\b\b"
}

# Warning about submodule changes
check_submodule_changes() {
  # Check if any submodules have changes
  if git submodule foreach git diff --quiet 2>/dev/null; then
    echo -e "${GREEN}✓ No changes detected in submodules${NC}"
  else
    echo -e "${YELLOW}⚠ WARNING: Changes detected in submodules!${NC}"
    echo -e "${YELLOW}Submodule changes are not typically committed unless deliberately updating them.${NC}"
    echo -e "${YELLOW}To discard submodule changes: git submodule foreach git reset --hard${NC}"
    echo -e "${YELLOW}To reinitialize submodules:  git submodule update --init --recursive${NC}"
  fi
}

echo -e "${BOLD}${BLUE}=== Yearn Strategy CI Checks ===${NC}"
echo -e "${YELLOW}Running GitHub Actions checks locally${NC}"
echo "========================================"

# Enable Corepack for proper package manager handling
echo -e "${YELLOW}Enabling Corepack for proper package manager handling...${NC}"
corepack enable

echo -e "${YELLOW}1. Running Prettier format check (excluding submodules)...${NC}"
pnpm format:check > /tmp/format_check.log 2>&1 &
format_pid=$!
spinner $format_pid
wait $format_pid
format_exit=$?
if [ $format_exit -eq 0 ]; then
  echo -e "${GREEN}✓ Format check passed${NC}"
else
  FORMAT_FAILED=true
  echo -e "${RED}✗ Format check failed${NC}"
  echo -e "${YELLOW}Note: Submodules (lib/ directory) are excluded from formatting${NC}"
fi

echo -e "${YELLOW}2. Running Solhint linter check (excluding submodules)...${NC}"
pnpm lint > /tmp/lint_check.log 2>&1 &
lint_pid=$!
spinner $lint_pid
wait $lint_pid
lint_exit=$?
if [ $lint_exit -eq 0 ]; then
  echo -e "${GREEN}✓ Linter check passed${NC}"
else
  LINT_FAILED=true
  echo -e "${RED}✗ Linter check failed${NC}"
  echo -e "${YELLOW}Note: Submodules (lib/ directory) are excluded from linting${NC}"
fi

echo -e "${YELLOW}3. Testing commit message format...${NC}"
# Test with sample commit message
echo "Sample commit with conventional format:"
echo "feat: sample commit message" | npx commitlint

# Check the last commit message if we're in a git repo
if [ -d .git ]; then
  echo -e "${YELLOW}Checking last actual commit message:${NC}"
  COMMIT_MSG=$(git log -1 --pretty=format:"%s")
  echo "$COMMIT_MSG"
  echo "$COMMIT_MSG" | npx commitlint > /tmp/commit_check.log 2>&1
  if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Commit format check passed${NC}"
  else
    COMMIT_FAILED=true
    echo -e "${RED}✗ Commit format check failed${NC}"
  fi
else
  echo "Not in a git repository, skipping git commit check"
fi

# Run Slither security analysis
echo -e "${YELLOW}4. Running Slither security analysis...${NC}"
# Check if slither is installed
if command -v slither &> /dev/null; then
  # Using similar settings as GitHub workflow
  echo -e "${YELLOW}Running Slither on StCVXCRVStrategy.sol...${NC}"

  # Remove any existing slither output to avoid the prevention of overwrite
  rm -f /tmp/slither_results.json

  # Run on StCVXCRVStrategy.sol
  slither src/StCVXCRVStrategy.sol --json /tmp/slither_results.json > /tmp/slither_check.log 2>&1
  SLITHER_EXIT_CODE=$?

  # Count number of medium or high findings
  if [ -f /tmp/slither_results.json ]; then
    # Use -s to suppress error messages when no matches are found
    HIGH_FINDINGS=$(grep -c -s '"impact": "High"' /tmp/slither_results.json || echo 0)
    MEDIUM_FINDINGS=$(grep -c -s '"impact": "Medium"' /tmp/slither_results.json || echo 0)

    # Make sure these are actual integers
    HIGH_FINDINGS=$(echo $HIGH_FINDINGS | tr -d '[:space:]')
    MEDIUM_FINDINGS=$(echo $MEDIUM_FINDINGS | tr -d '[:space:]')

    # Default to 0 if empty
    [ -z "$HIGH_FINDINGS" ] && HIGH_FINDINGS=0
    [ -z "$MEDIUM_FINDINGS" ] && MEDIUM_FINDINGS=0

    if [ "$HIGH_FINDINGS" -gt 0 ]; then
      echo -e "${RED}✗ Slither found $HIGH_FINDINGS high severity issues in StCVXCRVStrategy.sol${NC}"
      SLITHER_FAILED=true
    elif [ $SLITHER_EXIT_CODE -ne 0 ]; then
      echo -e "${RED}✗ Slither check on StCVXCRVStrategy.sol failed with exit code $SLITHER_EXIT_CODE${NC}"
      SLITHER_FAILED=true
    else
      echo -e "${GREEN}✓ Slither check on StCVXCRVStrategy.sol passed${NC}"
    fi
  else
    if [ $SLITHER_EXIT_CODE -ne 0 ]; then
      echo -e "${RED}✗ Slither check on StCVXCRVStrategy.sol failed with exit code $SLITHER_EXIT_CODE${NC}"
      SLITHER_FAILED=true
    else
      echo -e "${GREEN}✓ Slither check on StCVXCRVStrategy.sol passed${NC}"
    fi
  fi
else
  echo -e "${YELLOW}⚠ Slither not installed. Install with: pip3 install slither-analyzer${NC}"
fi  # First fix the commit message issue by modifying our HEAD commit
  if [ -d .git ] && [[ "$COMMIT_FAILED" == true ]]; then
    echo -e "${YELLOW}Attempting to fix the commit message automatically...${NC}"
    CURRENT_MSG=$(git log -1 --pretty=format:"%s")
    # Extract the message part, ignoring any type prefix
    MSG_CONTENT=$(echo "$CURRENT_MSG" | sed -E 's/^[a-z]+(\([a-z-]+\))?:\s*//i')
    if [[ -z "$MSG_CONTENT" ]]; then
      # If we couldn't extract content, use the whole message
      MSG_CONTENT="$CURRENT_MSG"
    fi

    # Suggest a fixed commit message
    FIXED_MSG="refactor: $MSG_CONTENT"
    echo -e "${YELLOW}Suggested fixed commit message: ${NC}$FIXED_MSG"
    echo -e "${YELLOW}To fix your commit message, run:${NC}"
    echo -e "  ${BLUE}git commit --amend -m \"$FIXED_MSG\"${NC}"
  fi

  # Optional - check for any uncommitted changes
  if [ -d .git ]; then
    echo -e "${YELLOW}5. Checking for uncommitted changes...${NC}"
    UNCOMMITTED=$(git status --porcelain | wc -l)
    if [ "$UNCOMMITTED" -eq 0 ]; then
      echo -e "${GREEN}✓ No uncommitted changes${NC}"
    else
      echo -e "${YELLOW}! You have $UNCOMMITTED uncommitted changes${NC}"
    fi

    # Check for submodule changes
    echo -e "${YELLOW}Checking for changes in submodules...${NC}"
    check_submodule_changes
  fi

# Run tests
echo -e "${YELLOW}6. Running Forge build...${NC}"
forge --version > /tmp/forge_version.log 2>&1
echo -e "${YELLOW}Forge version: ${NC}$(cat /tmp/forge_version.log)"
echo -e "${YELLOW}Running forge build --sizes${NC}"
forge build --sizes > /tmp/build_output.log 2>&1 &
build_pid=$!
spinner $build_pid
wait $build_pid
build_exit=$?

if [ $build_exit -eq 0 ]; then
  echo -e "${GREEN}✓ Build successful${NC}"
  # Display contract sizes
  echo -e "${YELLOW}Contract sizes:${NC}"
  grep "StCVXCRVStrategy" /tmp/build_output.log | head -n 3
elif grep -q "No files changed, compilation skipped" /tmp/build_output.log; then
  echo -e "${GREEN}✓ No files changed, compilation skipped${NC}"
  # Still display contract sizes if available
  if grep -q "StCVXCRVStrategy" /tmp/build_output.log; then
    echo -e "${YELLOW}Contract sizes:${NC}"
    grep "StCVXCRVStrategy" /tmp/build_output.log | head -n 3
  fi
else
  BUILD_FAILED=true
  echo -e "${RED}✗ Build failed${NC}"
  cat /tmp/build_output.log
fi

echo -e "${YELLOW}7. Running Forge tests...${NC}"
# Check if the FORK_URL environment variable is set
if [ -z "$FORK_URL" ] && [ -z "$ETH_RPC_URL" ]; then
  echo -e "${YELLOW}⚠ No FORK_URL or ETH_RPC_URL environment variable set${NC}"
  echo -e "${YELLOW}Please set one of these variables to run tests${NC}"
  echo -e "${YELLOW}Example: export FORK_URL=https://eth-mainnet.alchemyapi.io/v2/your-api-key${NC}"
  TEST_SKIPPED=true
else
  # Use FORK_URL if available, otherwise fall back to ETH_RPC_URL
  FORK_URL_TO_USE=${FORK_URL:-$ETH_RPC_URL}
  echo -e "${YELLOW}Running tests with fork URL: ${FORK_URL_TO_USE}${NC}"

  # Run the tests and capture both exit code and output
  echo -e "${YELLOW}Running forge test -vv --fork-url ${FORK_URL_TO_USE}${NC}"
  forge test -vv --fork-url ${FORK_URL_TO_USE} > /tmp/test_output.log 2>&1 &
  test_pid=$!
  spinner $test_pid
  wait $test_pid
  test_exit=$?

  if [ $test_exit -eq 0 ]; then
    echo -e "${GREEN}✓ All tests passed${NC}"
    # Display the number of passing tests
    TESTS_PASSED=$(grep -o "Test result: ok" /tmp/test_output.log | wc -l)
    TEST_COUNT=$(grep -o "Ran [0-9]* test" /tmp/test_output.log | grep -o "[0-9]*")
    echo -e "${GREEN}✓ $TEST_COUNT tests completed successfully${NC}"
  else
    TEST_FAILED=true
    echo -e "${RED}✗ Tests failed${NC}"
    # Show failing tests
    echo -e "${RED}Failing tests:${NC}"
    grep -A 5 "FAIL\|Error:" /tmp/test_output.log | head -n 20
    echo -e "${YELLOW}See complete log in /tmp/test_output.log${NC}"
  fi
fi

# Run coverage
echo -e "${YELLOW}8. Generating test coverage...${NC}"
# Skip if no fork URL is available or if tests failed
if [ "$TEST_SKIPPED" = true ]; then
  echo -e "${YELLOW}⚠ Skipping coverage as FORK_URL is not set${NC}"
  COVERAGE_SKIPPED=true
elif [ "$BUILD_FAILED" = true ]; then
  echo -e "${YELLOW}⚠ Skipping coverage as build failed${NC}"
  COVERAGE_SKIPPED=true
elif [ "$TEST_FAILED" = true ] && [ "$1" != "--run-coverage-anyway" ] && [ "$2" != "--run-coverage-anyway" ]; then
  echo -e "${YELLOW}⚠ Skipping coverage as tests failed${NC}"
  echo -e "${YELLOW}You can force coverage generation with:${NC}"
  echo -e "  ${BLUE}./run_ci_locally.sh --run-coverage-anyway${NC}"
  COVERAGE_SKIPPED=true
else
  # Use FORK_URL if available, otherwise fall back to ETH_RPC_URL
  FORK_URL_TO_USE=${FORK_URL:-$ETH_RPC_URL}

  # Generate coverage report
  echo -e "${YELLOW}Generating LCOV coverage report...${NC}"
  echo -e "${YELLOW}Running forge coverage --report lcov --fork-url ${FORK_URL_TO_USE}${NC}"
  forge coverage --report lcov --fork-url ${FORK_URL_TO_USE} > /tmp/coverage_output.log 2>&1 &
  coverage_pid=$!
  spinner $coverage_pid
  wait $coverage_pid
  coverage_exit=$?

  if [ $coverage_exit -eq 0 ]; then
    echo -e "${GREEN}✓ Coverage report generated${NC}"

    # Generate summary (similar to GitHub Actions workflow)
    echo -e "${YELLOW}Generating coverage summary...${NC}"

    # Check if lcov is installed
    if command -v lcov &> /dev/null; then
      # Make sure the lcov.info file exists
      if [ -f "lcov.info" ]; then
        lcov --summary lcov.info > /tmp/coverage_summary.log 2>&1
        if [ $? -eq 0 ]; then
          echo -e "${GREEN}=== Coverage Summary ===${NC}"
          cat /tmp/coverage_summary.log

          # Extract and display the overall line coverage percentage
          LINE_COVERAGE=$(grep "lines......:" /tmp/coverage_summary.log | awk '{print $2}')
          if [ -n "$LINE_COVERAGE" ]; then
            echo -e "${GREEN}Overall line coverage: ${LINE_COVERAGE}${NC}"
          fi
        else
          echo -e "${YELLOW}⚠ Could not generate coverage summary${NC}"
          echo -e "${YELLOW}See error details in: /tmp/coverage_summary.log${NC}"
        fi
      else
        echo -e "${YELLOW}⚠ No lcov.info file found after coverage run${NC}"
      fi

      # Check if we should generate HTML report
      if [ "$1" = "--html-coverage" ] || [ "$2" = "--html-coverage" ]; then
        echo -e "${YELLOW}Generating HTML coverage report...${NC}"
        mkdir -p coverage-report

        make coverage-html > /dev/null 2>&1

        if [ $? -eq 0 ]; then
          echo -e "${GREEN}✓ HTML coverage report generated${NC}"
          echo -e "${YELLOW}Report available at: ${NC}coverage-report/index.html"
          echo -e "${YELLOW}Note: Coverage reports should not be committed to Git${NC}"
        else
          echo -e "${RED}✗ Failed to generate HTML coverage report${NC}"
        fi
      else
        echo -e "${YELLOW}Note: You can generate an HTML coverage report with:${NC}"
        echo -e "  ${BLUE}./run_ci_locally.sh --html-coverage${NC}"
      fi
    else
      echo -e "${YELLOW}⚠ lcov not installed. Install with: sudo apt-get install lcov (Ubuntu) or brew install lcov (macOS)${NC}"
    fi
  else
    COVERAGE_FAILED=true
    echo -e "${RED}✗ Coverage generation failed${NC}"
  fi
fi

echo "========================================"

if [ "$FORMAT_FAILED" = true ] || [ "$LINT_FAILED" = true ] || [ "$COMMIT_FAILED" = true ] || [ "$SLITHER_FAILED" = true ] || [ "$BUILD_FAILED" = true ] || [ "$TEST_FAILED" = true ] || [ "$COVERAGE_FAILED" = true ]; then
  echo -e "${RED}❌ Some checks failed!${NC}"
  [ "$FORMAT_FAILED" = true ] && echo -e "${RED}  - Format check failed${NC}" && cat /tmp/format_check.log
  [ "$LINT_FAILED" = true ] && echo -e "${RED}  - Linter check failed${NC}" && cat /tmp/lint_check.log
  [ "$COMMIT_FAILED" = true ] && echo -e "${RED}  - Commit format check failed${NC}" && cat /tmp/commit_check.log
  [ "$BUILD_FAILED" = true ] && echo -e "${RED}  - Build failed${NC}" && cat /tmp/build_output.log
  [ "$TEST_FAILED" = true ] && echo -e "${RED}  - Tests failed${NC}" && cat /tmp/test_output.log
  [ "$COVERAGE_FAILED" = true ] && echo -e "${RED}  - Coverage generation failed${NC}" && cat /tmp/coverage_output.log

  if [ "$SLITHER_FAILED" = true ]; then
    echo -e "${RED}  - Slither security check failed${NC}"
    if [ -f /tmp/slither_results.json ]; then
      echo -e "${RED}    Medium/High severity findings:${NC}"
      grep -A 10 -B 2 '"impact": "High"\|"impact": "Medium"' /tmp/slither_results.json | grep -E '"check"|"impact"|"description"|"elements"' | sed 's/^/      /'
    else
      cat /tmp/slither_check.log
    fi

    # Add an option to bypass slither checks when needed during development
    if [ "$1" = "--ignore-slither" ]; then
      echo -e "${YELLOW}Ignoring Slither failures due to --ignore-slither flag${NC}"
      SLITHER_FAILED=false
    else
      echo -e "${YELLOW}Note: You can bypass Slither checks during development with:${NC}"
      echo -e "  ${BLUE}./run_ci_locally.sh --ignore-slither${NC}"
    fi
  fi

  echo ""
  echo -e "${YELLOW}Recommendations:${NC}"
  [ "$FORMAT_FAILED" = true ] && echo "  - Run 'yarn format' to fix formatting issues"
  [ "$LINT_FAILED" = true ] && echo "  - Run 'yarn lint:fix' to fix linting issues"
  [ "$COMMIT_FAILED" = true ] && echo "  - Format your commit messages as: 'type(scope): message'"
  [ "$COMMIT_FAILED" = true ] && echo "    Valid types: feat, fix, docs, style, refactor, perf, test, ci, chore, revert"
  [ "$SLITHER_FAILED" = true ] && echo "  - Check full Slither output in /tmp/slither_check.log"
  [ "$SLITHER_FAILED" = true ] && echo "  - Fix medium and high severity security issues before committing"
  [ "$BUILD_FAILED" = true ] && echo "  - Fix build errors before running tests"
  [ "$BUILD_FAILED" = true ] && echo "  - Check full build output in /tmp/build_output.log"
  [ "$TEST_FAILED" = true ] && echo "  - Fix failing tests before committing"
  [ "$TEST_FAILED" = true ] && echo "  - Check full test output in /tmp/test_output.log"
  [ "$COVERAGE_FAILED" = true ] && echo "  - Check coverage output in /tmp/coverage_output.log"
  [ "$TEST_SKIPPED" = true ] || [ "$COVERAGE_SKIPPED" = true ] && echo "  - Set FORK_URL environment variable to run tests and coverage"

  # Check for submodule changes and provide recommendation
  if ! git submodule foreach git diff --quiet 2>/dev/null; then
    echo "  - Submodule changes detected. If unintentional, run:"
    echo "    git submodule foreach git reset --hard"
    echo "    git submodule update --init --recursive"
  fi

  # Only exit with error if there are still failures after processing flags
  if [ "$FORMAT_FAILED" = true ] || [ "$LINT_FAILED" = true ] || [ "$COMMIT_FAILED" = true ] || [ "$SLITHER_FAILED" = true ] || [ "$BUILD_FAILED" = true ] || [ "$TEST_FAILED" = true ] || [ "$COVERAGE_FAILED" = true ]; then
    exit 1
  fi
else
  echo -e "${GREEN}✅ All checks passed!${NC}"
  if [ "$TEST_SKIPPED" = true ] || [ "$COVERAGE_SKIPPED" = true ]; then
    echo -e "${YELLOW}⚠ Some checks were skipped${NC}"
    [ "$TEST_SKIPPED" = true ] && echo -e "${YELLOW}  - Tests were skipped${NC}"
    [ "$COVERAGE_SKIPPED" = true ] && echo -e "${YELLOW}  - Coverage was skipped${NC}"
    echo -e "${YELLOW}Set FORK_URL environment variable to run all checks${NC}"
  else
    echo -e "${GREEN}Your code is ready to be committed!${NC}"
  fi

  # Check if there are uncommitted changes
  if [ -d .git ] && [ "$(git status --porcelain | wc -l)" -ne 0 ]; then
    echo -e "${YELLOW}Don't forget to commit your changes:${NC}"
    echo -e "  ${BLUE}git add .${NC}"
    echo -e "  ${BLUE}git commit -m \"feat: your meaningful commit message\"${NC}"
  fi

  exit 0
fi
