name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  solidity:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # Enable Corepack to use the packageManager specified in package.json
      - name: Enable Corepack
        run: corepack enable

      - name: Set pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Restore pnpm cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
            ${{ runner.os }}-pnpm-
      - name: Install node.js dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run formater check on *.sol and *.json
        run: pnpm format:check

      - name: run linter check on *.sol file
        run: pnpm lint

  commits:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5
