name: test

on:
  push:
    branches:
      - master
      - develop
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Debug ETH_RPC_URL
        run: |
          if [ -z "$ETH_RPC_URL" ]; then
            echo "ETH_RPC_URL is not set"
            exit 1
          else
            echo "ETH_RPC_URL is set"
          fi
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          export ETH_RPC_URL=${{ secrets.ETH_RPC_URL }}
          forge test -vvv --fork-url $ETH_RPC_URL
        id: test
